name: Deploy 
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy
        run: | 
          echo "Deploying to ${{ vars.PROD_DOMAIN }}"
          echo "::notice::Deploy concluído" 
